### ISSUE TITLE
there is no Notebook VM in the panes anymore

### ISSUE THREAD

**Issue by sasever** [marvinbuss/AzureMLWorkshop#2]
![image](https://user-images.githubusercontent.com/43384573/91012673-25106f80-e5ef-11ea-8014-4295ac3568e0.png)
https://github.com/marvinbuss/AzureMLWorkshop#provision-notebook-vm

notebook VM pane does not exist in the newly generated AML environments.

**Comment by marvinbuss** [comment]
Thanks. Yes, you are right. We need to fix this in the docs.
In which notebook does this appear? Just the intro notebook?

**Comment by sasever** [comment]
Just intro as I noticed, Ill add if I see anything else.
